#crab submit TT.py
#crab submit WJtoQQ2.py
#crab submit WW.py
#crab submit WZ.py
crab submit ZJtoQQ.py
#crab submit ZZ.py
#crab submit ST.py
#crab submit crab3_analysisST_t-channel_antitop_4f_inclusiveDecays.py
#crab submit crab3_analysisST_t-channel_top_4f_inclusiveDecays.py
#crab submit crab3_analysisST_tW_antitop_5f_inclusiveDecays.py
#crab submit crab3_analysisST_tW_top_5f_inclusiveDecays.py
crab submit QCDHT1000to1500.py
crab submit QCDHT1000to1500ext.py
crab submit QCDHT1500to2000.py
crab submit QCDHT1500to2000ext.py
crab submit QCDHT2000toInf.py
crab submit QCDHT2000toInfext.py
